const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
const PRODUCT_LIST_REQUEST_SUCCESS = 'PRODUCT_LIST_REQUEST_SUCCESS';
const PRODUCT_LIST_REQUEST_FAIL = 'PRODUCT_LIST_REQUEST_FAIL';

const SINGLE_PRODUCT_REQUEST = 'SINGLE_PRODUCT_REQUEST';
const SINGLE_PRODUCT_REQUEST_SUCCESS = 'SINGLE_PRODUCT_REQUEST_SUCCESS';
const SINGLE_PRODUCT_REQUEST_FAIL = 'SINGLE_PRODUCT_REQUEST_FAIL';

export {PRODUCT_LIST_REQUEST, PRODUCT_LIST_REQUEST_SUCCESS, PRODUCT_LIST_REQUEST_FAIL};
export {SINGLE_PRODUCT_REQUEST, SINGLE_PRODUCT_REQUEST_SUCCESS, SINGLE_PRODUCT_REQUEST_FAIL};
